[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@matterlabs/zksync-contracts=lib/zksync-era/contracts/system-contracts/contracts/",
    "forge-std=lib/forge-std/src/",
    "murky=lib/zksync-era/contracts/lib/murky/"
]
